spring:
    profiles: prod

environment: prod
name: Production
url: localhost
port: 8080

mongo:
  clusterHost: ${MONGO_HOST}
  port: ${MONGO_PORT}
  dbName: ${MONGO_DB_NAME}
  auth: ${MONGO_AUTH}
  user: ${MONGO_USER}
  password: ${MONGO_PASSWORD}