spring:
    profiles: prod

environment: prod
name: Production
url: localhost
port: 8080

mongo:
  clusterHost: ${MONGO_HOST}
  port: ${MONGO_PORT}
  dbName: ${MONGO_DB_NAME}
  auth: ${MONGO_AUTH}
  user: ${MONGO_USER}
  password: ${MONGO_PASSWORD}
  
email:
  user: ${MAIL_USR}
  password: ${MAIL_PSW}
  smtpHost: ${MAIL_SMTP_HOST}
  smtpPort: ${MAIL_SMTP_PORT}
  smtpSSLEnabled: ${MAIL_SMTP_SSL}
  smtpAuth: ${MAIL_SMTP_AUTH}
  
threshold:
  gas: 1500